% Auto-generated by cameraCalibrator app on 14-Feb-2023
%-------------------------------------------------------


% Define images to process
imageFileNames = {'C:\Users\singh\OneDrive\Desktop\camera_calibration\Image1.png',...
    'C:\Users\singh\OneDrive\Desktop\camera_calibration\Image2.png',...
    'C:\Users\singh\OneDrive\Desktop\camera_calibration\Image3.png',...
    'C:\Users\singh\OneDrive\Desktop\camera_calibration\Image4.png',...
    'C:\Users\singh\OneDrive\Desktop\camera_calibration\Image5.png',...
    'C:\Users\singh\OneDrive\Desktop\camera_calibration\Image6.png',...
    'C:\Users\singh\OneDrive\Desktop\camera_calibration\Image7.png',...
    'C:\Users\singh\OneDrive\Desktop\camera_calibration\Image8.png',...
    'C:\Users\singh\OneDrive\Desktop\camera_calibration\Image9.png',...
    'C:\Users\singh\OneDrive\Desktop\camera_calibration\Image10.png',...
    };
% Detect calibration pattern in images
detector = vision.calibration.monocular.CheckerboardDetector();
[imagePoints, imagesUsed] = detectPatternPoints(detector, imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates for the planar pattern keypoints
squareSize = 25;  % in units of 'millimeters'
worldPoints = generateWorldPoints(detector, 'SquareSize', squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
h1=figure; cameraParashowReprojectionErrors(ms);

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
undistortedImage = undistortImage(originalImage, cameraParams);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')
